60: overzicht kinderen
PXL-PRiSMA/PRiSMA pull request #10
Opened 2022-11-07 22:24 UTC by MaudeVanhengelPXL

## 60: Als gebruiker wil ik een overzicht van al mijn toegewezen kinderen zien staan
[Jira link](https://jiradigi.pxl.be/browse/IT2223T14-60)

**frontend**
- 'overzicht kinderen'pagina toegevoegd
- routing toegevoegd
- service voor api call toegevoegd
- error interceptor toegevoegd om errors goed op te vangen en weer te geven

**backend**
- controller toegevoegd om op basis van user alle kinderen op te halen
- domein modellen aangemaakt
- service en repository toegevoegd
- configuratie van de database
- database invullen met mock data via flyway scripts
- tests toegevoegd voor service en controller
- configuratie .env file
- README.md aangevuld
- swagger-ui toegevoegd

## Checklist voor het openzetten van de PR:
- [X] Ik heb mijn code zelf reviewed.
- [X] Ik heb tests voor mijn code toegevoegd (coverage >= 70%).
- [X] Bestaande en nieuwe tests slagen allemaal.
- [X] Er zijn geen breaking changes.
- [X] De code compileert en kan lokaal gebuild en gerund worden.

2022-11-09 16:41 UTC, MaximDeCuyperPXL approved these changes
Doorheen de code wordt overal 'user' gebruikt. Moeten we dit aanpassen naar 'gebruiker' aangezien we overal Nederlands gebruiken of laten we user als een uitzondering?
Voor de rest alles oké!

2022-11-09 20:04 UTC, JonasVerlindenPXL requested changes
comments weghalen in kind-card.component.html
voor de rest ziet het er goed uit

2022-11-09 23:25 UTC, MaudeVanhengelPXL commented
> comments weghalen in kind-card.component.html voor de rest ziet het er goed uit

Done!

2022-11-09 23:41 UTC, MaudeVanhengelPXL commented
dev gemerged naar deze branch ivm .github/workflows die in dev werden geüpdatet

2022-11-10 07:57 UTC, JonasVerlindenPXL approved these changes
comments bijgewerkt. alles in orde nu

2022-11-10 07:57 UTC, merged